### ISSUE TITLE
new Module.maxiOsc() with eval

### ISSUE THREAD

**Issue by frantic0** [mimic-sussex/Maximilian#10]
I get an error when I evaluate a maxiOsc constructor with a sinewave.

() => { return new Module.maxiOsc().sinewave(400)}

```
Uncaught abort("Cannot enlarge memory arrays to size 16781312 bytes. Either 
(1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, 
(2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, 
(3) set Module.TOTAL_MEMORY to a higher value before the program runs, or 
(4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at 
Error
    at jsStackTrace (http://localhost:8000/audioWorklet/maxi-processor-eval-message/maximilian.wasmmodule.js:1080:13)
    at stackTrace (http://localhost:8000/audioWorklet/maxi-processor-eval-message/maximilian.wasmmodule.js:1097:12)
    at abort (http://localhost:8000/audioWorklet/maxi-processor-eval-message/maximilian.wasmmodule.js:90131:44)
    at abortOnCannotGrowMemory (http://localhost:8000/audioWorklet/maxi-processor-eval-message/maximilian.wasmmodule.js:6732:7)
    at _emscripten_resize_heap (http://localhost:8000/audioWorklet/maxi-processor-eval-message/maximilian.wasmmodule.js:6734:7)
    at _sbrk (http://localhost:8000/audioWorklet/maxi-processor-eval-message/maximilian.wasmmodule.js:88767:12)
    at _malloc (http://localhost:8000/audioWorklet/maxi-processor-eval-message/maximilian.wasmmodule.js:42736:15)
    at __Znwm (http://localhost:8000/audioWorklet/maxi-processor-eval-message/maximilian.wasmmodule.js:85087:9)
    at Array.__ZN10emscripten8internal18GenericBindingTypeINSt3__210shared_ptrI7maxiOscEEE10toWireTypeEOS5_ (http://localhost:8000/audioWorklet/maxi-processor-eval-message/maximilian.wasmmodule.js:15443:8)
    at dynCall_ii (http://localhost:8000/audioWorklet/maxi-processor-eval-message/maximilian.wasmmodule.js:88982:38)

(index):75 WASMWorkletProcessor Error detected
```

**Comment by frantic0** [comment]
Compiling with **-s ALLOW_MEMORY_GROWTH=1**
```
CFLAGS=--bind -O1 \
 		-s DISABLE_EXCEPTION_CATCHING=0 \
		-s ALLOW_MEMORY_GROWTH=1 \
		-s ASSERTIONS=1 \
		-s WASM=0 \
		-s BINARYEN_ASYNC_COMPILATION=0 \
		-s SINGLE_FILE=1
```

When it hits a constructor instruction (e.g. `new Module.maxiOsc()`) I get the warning below:

```
Warning: Enlarging memory arrays, this is not fast! 16777216,33554432
```
